"""Export an interactive GLB visualization of one HAP-Place result.

Run this command in the WSL ``scenerevis`` environment. It reads the geometry
handoff generated by ``run_hap_place.py`` and does not rebuild the room.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any, Dict, Mapping, Optional, Sequence

import numpy as np
import trimesh


COLORS = {
    "scene": np.array([150, 155, 164, 255], dtype=np.uint8),
    "target": np.array([48, 180, 105, 255], dtype=np.uint8),
    "surface_hit": np.array([232, 116, 38, 255], dtype=np.uint8),
    "release": np.array([35, 112, 210, 255], dtype=np.uint8),
    "ground_truth": np.array([190, 65, 155, 255], dtype=np.uint8),
}


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Export a HAP-Place result as an interactive GLB")
    parser.add_argument("--result_json", required=True)
    parser.add_argument("--output_glb", required=True)
    parser.add_argument("--sample_id", default=None)
    parser.add_argument("--sample_index", type=int, default=0)
    parser.add_argument("--hide_gt", action="store_true")
    return parser.parse_args()


def _load_json(path: Path) -> Any:
    with open(path, "r", encoding="utf-8") as handle:
        return json.load(handle)


def _select_result(payload: Mapping[str, Any], sample_id: Optional[str], sample_index: int) -> Dict[str, Any]:
    results = payload.get("results", [])
    if sample_id is not None:
        for result in results:
            if str(result.get("sample_id")) == sample_id:
                return dict(result)
        raise KeyError(f"No result with sample_id={sample_id!r}")
    if sample_index < 0 or sample_index >= len(results):
        raise IndexError(f"sample_index {sample_index} is outside 0..{len(results) - 1}")
    return dict(results[sample_index])


def _resolve_path(path_text: str, result_json: Path) -> Path:
    path = Path(path_text)
    if path.exists():
        return path
    candidate = result_json.parent / path
    if candidate.exists():
        return candidate
    raise FileNotFoundError(path)


def _mesh(vertices: np.ndarray, faces: np.ndarray, color: np.ndarray) -> trimesh.Trimesh:
    mesh = trimesh.Trimesh(vertices=vertices, faces=faces, process=False)
    mesh.visual.face_colors = color
    return mesh


def _sphere(point: Sequence[float], radius: float, color: np.ndarray) -> trimesh.Trimesh:
    marker = trimesh.creation.icosphere(subdivisions=2, radius=radius)
    marker.apply_translation(np.asarray(point, dtype=np.float64))
    marker.visual.face_colors = color
    return marker


def _cylinder_between(
    start: Sequence[float],
    end: Sequence[float],
    radius: float,
    color: np.ndarray,
) -> Optional[trimesh.Trimesh]:
    start_array = np.asarray(start, dtype=np.float64)
    end_array = np.asarray(end, dtype=np.float64)
    vector = end_array - start_array
    length = float(np.linalg.norm(vector))
    if length <= 1e-9:
        return None
    cylinder = trimesh.creation.cylinder(radius=radius, height=length, sections=12)
    rotation = trimesh.geometry.align_vectors([0.0, 0.0, 1.0], vector)
    if rotation is None:
        rotation = np.eye(4, dtype=np.float64)
    rotation[:3, 3] = (start_array + end_array) * 0.5
    cylinder.apply_transform(rotation)
    cylinder.visual.face_colors = color
    return cylinder


def _prepared_to_world(result: Mapping[str, Any]) -> np.ndarray:
    physics = result.get("physics")
    if isinstance(physics, Mapping) and physics.get("final_transform_prepared_to_world") is not None:
        transform = np.asarray(physics["final_transform_prepared_to_world"], dtype=np.float64)
    else:
        release = result.get("release_search", {}).get("release_bottom_world_xyz")
        if release is None:
            raise ValueError("Result has no release pose")
        transform = np.eye(4, dtype=np.float64)
        transform[:3, 3] = np.asarray(release, dtype=np.float64)
    if transform.shape != (4, 4) or not np.all(np.isfinite(transform)):
        raise ValueError("Prepared-to-world transform must be a finite 4x4 matrix")
    return transform


def _lookup_gt_position(payload: Mapping[str, Any], result: Mapping[str, Any]) -> Optional[np.ndarray]:
    config = payload.get("config", {})
    data_dir = config.get("data_dir")
    split = config.get("split")
    if not data_dir or not split:
        return None
    split_path = Path(data_dir) / str(split) / f"{split}.json"
    if not split_path.exists():
        return None
    sample_id = str(result.get("sample_id"))
    for sample in _load_json(split_path):
        if str(sample.get("sample_id")) != sample_id:
            continue
        position = sample.get("removed_object", {}).get("pos")
        if isinstance(position, list) and len(position) == 3:
            return np.asarray(position, dtype=np.float64)
        return None
    return None


def main() -> None:
    args = parse_args()
    result_json = Path(args.result_json)
    payload = _load_json(result_json)
    result = _select_result(payload, args.sample_id, args.sample_index)
    if result.get("valid_output") is not True:
        raise ValueError(
            f"Cannot visualize failed result: {result.get('failure_code', result.get('status'))}"
        )

    manifest_path = _resolve_path(str(result["physics_manifest"]), result_json)
    manifest = _load_json(manifest_path)
    geometry_path = _resolve_path(str(manifest["geometry_npz"]), manifest_path)
    geometry = np.load(geometry_path)

    scene_mesh = _mesh(geometry["scene_vertices"], geometry["scene_faces"], COLORS["scene"])
    target_mesh = _mesh(geometry["target_vertices"], geometry["target_faces"], COLORS["target"])
    target_mesh.apply_transform(_prepared_to_world(result))

    grid = result.get("voxel_grid", {})
    pitch = float(grid.get("pitch", 0.02))
    marker_radius = max(pitch * 0.8, 0.008)
    line_radius = max(pitch * 0.2, 0.002)
    search = result["release_search"]
    surface_hit = np.asarray(search["surface_hit_world_xyz"], dtype=np.float64)
    release = np.asarray(search["release_bottom_world_xyz"], dtype=np.float64)

    visualization = trimesh.Scene()
    visualization.add_geometry(scene_mesh, geom_name="existing_scene")
    visualization.add_geometry(target_mesh, geom_name="hap_target")
    visualization.add_geometry(
        _sphere(surface_hit, marker_radius, COLORS["surface_hit"]),
        geom_name="first_visible_surface_hit",
    )
    visualization.add_geometry(
        _sphere(release, marker_radius, COLORS["release"]),
        geom_name="release_bottom_anchor",
    )
    clearance_line = _cylinder_between(
        surface_hit,
        release,
        line_radius,
        COLORS["release"],
    )
    if clearance_line is not None:
        visualization.add_geometry(clearance_line, geom_name="surface_to_release")

    gt_position = None if args.hide_gt else _lookup_gt_position(payload, result)
    if gt_position is not None:
        visualization.add_geometry(
            _sphere(gt_position, marker_radius, COLORS["ground_truth"]),
            geom_name="ground_truth_anchor",
        )
        prediction_to_gt = _cylinder_between(
            release,
            gt_position,
            line_radius,
            COLORS["ground_truth"],
        )
        if prediction_to_gt is not None:
            visualization.add_geometry(prediction_to_gt, geom_name="prediction_to_ground_truth")

    extent = float(np.max(scene_mesh.extents))
    axis = trimesh.creation.axis(
        origin_size=max(extent * 0.006, 0.01),
        axis_radius=max(extent * 0.002, 0.003),
        axis_length=max(extent * 0.12, 0.25),
    )
    if isinstance(axis, trimesh.Scene):
        for name, geometry_part in axis.geometry.items():
            visualization.add_geometry(geometry_part, geom_name=f"world_axes_{name}")
    else:
        visualization.add_geometry(axis, geom_name="world_axes_xyz")

    output_path = Path(args.output_glb)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    visualization.export(output_path, file_type="glb")

    summary = {
        "sample_id": result.get("sample_id"),
        "pose_stage": result.get("simulator_record", {}).get("pose_stage"),
        "output_glb": str(output_path),
        "colors": {name: value.tolist() for name, value in COLORS.items()},
        "ground_truth_included": gt_position is not None,
    }
    print(json.dumps(summary, ensure_ascii=False, indent=2))


if __name__ == "__main__":
    main()
